trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - Examples/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

steps:
  - task: UseDotNet@2
    displayName: ".NET Core 3.1.x"
    inputs:
      version: '3.1.x'
      packageType: sdk
  
  - script: |
      dotnet tool update --version 1.0.0-rc0001 --tool-path ./tools Cake.Tool
      ./tools/dotnet-cake --Target RunNScanUnitTests
  
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
  
  - task: PublishBuildArtifacts@1