global using System.Collections.Generic;
global using AwesomeAssertions;
global using NSubstitute;
global using TddXt.AnyRoot;
global using TddXt.AnyRoot.Collections;
global using TddXt.AnyRoot.Numbers;
global using TddXt.AnyRoot.Strings;
global using TddXt.XNSubstitute;
global using Xunit;
global using static TddXt.AnyRoot.Root;
